[package]
name = "foundry-resolc"
description = "Resolc integration with foundry"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
foundry-config.workspace = true
foundry-compilers = { workspace = true, features = ["svm-solc"] }
alloy-primitives.workspace = true
tracing.workspace = true
serde_json.workspace = true
serde.workspace = true
semver.workspace = true
revm-inspectors.workspace = true
revive-solidity.workspace= true
eyre = "0.6"
